app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/


// Route::group(array('before' => 'api', 'after' => 'api-out'), function() {
// 	Route::get('api', 'APIController@api');
// 	Route::get('api/spots', 'APIController@spots');
// 	Route::get('api/actuators', 'APIController@actuators');
// 	Route::get('api/nonzone_spots', 'APIController@nonzone_spots');
// });

// Route::get('api/5', 'APIController@api');

Route::any('api/login', 'APIController@login');


Route::group(array('before' => 'guest'), function() {
	Route::controller('login', 'LoginController');
});

Route::group(array('before' => 'auth|admin'), function() {

	Route::get('admin/logout', 'LoginController@getLogout');

	Route::get('admin/basestations/{id}/unassign', 'BasestationController@getUnassignBasestation');
	Route::get('admin/basestations/{id}/edit', 'BasestationController@getEditBasestation');
	Route::get('admin/basestations/{id}', 'BasestationController@getBasestation');
	Route::post('admin/basestations/{id}', 'BasestationController@postEditBasestation');
	Route::controller('admin/basestations/', 'BasestationController');

 	Route::get('admin/spots', 'AdminController@getSpots');

	Route::get('admin/users/create', 'UserController@getCreateUser');
	Route::post('admin/users/create', 'UserController@postCreateUser');
	Route::get('admin/users/{id}/edit', 'UserController@getEditUser');
	Route::get('admin/users/{id}', 'UserController@getUser');
	Route::post('admin/users/{id}', 'UserController@postEditUser');
	Route::controller('admin/users/', 'UserController');

	Route::controller('admin', 'AdminController');
});

Route::group(array('before' => 'auth|basestation|spot|user'), function() {

	Route::get('api/getCurrentUser', 'APIController@getAuth');
	Route::get('api/getCurrentUserId', 'APIController@getAuthId');
	Route::get('api/logout', 'APIController@logout');
	Route::any('api/setActuatorStatus', 'APIController@setActuatorStatus');
	Route::get('api/getData/ZoneSpot', 'APIController@getDataForZoneSpot');
	Route::get('api/getData/RoamingSpot', 'APIController@getDataForRoamingSpot');
	Route::get('api/getData/ObjectSpot', 'APIController@getDataForObjectSpot');
	Route::get('api/{id}', 'APIController@api');

	Route::get('spots/{id}/stop_tracking', 'SpotController@getStopTracking');
	Route::resource('spots', 'SpotController');
	Route::controller('spots', 'SpotController');

	Route::get('objects/{id}/unlink', 'ObjectController@getUnlink');
	Route::resource('objects', 'ObjectController');

	Route::post('jobs/clear/{id}', 'JobController@clear');
	Route::post('jobs/toggle_tracking/{id}', 'JobController@toggle_tracking');
	Route::resource('jobs', 'JobController');

	Route::get('actuators/{id}/time', 'ActuatorController@getActuatorTimes');
	Route::post('actuators/{id}/settime', 'ActuatorController@postActuatorTime');
	Route::get('actuators/{id}/ajax', 'ActuatorController@getAjax');
	Route::get('actuators/conditions/{id}', 'ActuatorController@getConditions');
	Route::post('actuators/boolean_condition/{id}', 'ActuatorController@setBoolean');
	Route::post('actuators/add_condition/{id}', 'ActuatorController@addCondition');
	Route::post('actuators/delete_condition/{id}', 'ActuatorController@deleteCondition');
	Route::post('actuators/delete_job/{id}', 'ActuatorController@deleteJob');
	Route::post('actuators/set_status', 'ActuatorController@postSetStatus');
	Route::resource('actuators', 'ActuatorController');

	Route::post('zones/configure/addZone', array('as' =>'zones.configure.add_zone' , 'uses' => 'ZoneController@postAddZone'));
	Route::post('zones/configure/addObject', array('as' =>'zones.configure.add_object' , 'uses' => 'ZoneController@postAddObject'));
	Route::get('zones/configure', array('as' =>'zones.configure' , 'uses' => 'ZoneController@getZoneConfigure'));
	Route::post('zones/{id}/updateObject', array('as' =>'zones.update_object' , 'uses' => 'ZoneController@postUpdateObject'));
	Route::post('zones/{id}/updateZone', array('as' =>'zones.update_zone' , 'uses' => 'ZoneController@postUpdateZone'));
	Route::controller('zones', 'ZoneController');
	Route::resource('zones', 'ZoneController');

	Route::controller('reports', 'ReportController');
	Route::resource('reports', 'ReportController');

	Route::get('logout', 'LoginController@getLogout');
	Route::controller('/', 'TouchController');
});

app/models/Spot.php
<?php 
class Spot extends Eloquent {
    protected $table = 'Spot';

    /**
     * Override all() method to return spots with basestation user id of logged in user.
     * If logged in user is admin, return all spots 
     * @return [type] [description]
     */
    public static function all($columns = array()) {
    	if(Auth::user()->isAdmin())
    		return parent::all(); 
    	else
    		return Basestation::whereUserId(Auth::user()->id)->first()->spots; 
    }

    /**
     * Override find() method to return spots with basestation user id of logged in user.
     * If logged in user is admin, return spot by id
     * @return [type] [description]
     */
    public static function find($id, $columns = array()) {
    	if(Auth::user()->isAdmin())
    		return parent::find($id); 

    	$spot = Spot::whereId($id)->first(); 


    	if(isset($spot->id) && isset($spot->basestation->id) && $spot->basestation->user_id == Auth::user()->id)
    		return $spot; 
    	else
    		return false; 
    }

    /**
	 * Get this spot's user 
	 */
	public function user()
	{
		return $this->belongsTo('User');
	}

	 /**
	 * Get this spot's basestation 
	 */
	public function basestation()
	{
		return $this->belongsTo('Basestation');
	}

	/**
	 * Get this spot's objects
	 */
	public function object()
	{
		return $this->hasOne('Object');
	}

	/**
	 * Get this spot's jobs
	 */
	public function jobs()
	{
		return $this->hasManyThrough('Job', 'Object');
	}

	/**
	 * Get this spot's zone changes
	 */
	public function zonechanges()
	{
		return $this->hasMany('ZoneSpot');
	}

	/**
	 * Returns this spot's switch events
	 */
	public function switches() 
	{
		return $this->hasMany('Switches', 'spot_address', 'spot_address');
	}

	public function isSmartCup() 
	{
		foreach($this->jobs as $job)
			if($job->sensor->title == "Smart Cup") return true;
		return false;
	}

	/**
	 * Returns this spot's battery level. Maps 75-85 to 0-100
	 * (value-start)*100/(end-start)
	 */
	public function getBatteryPercentAttribute($value)
	{
		$start = 71;
		$end = 85; 

		if(!$value) return 0;
		
		$percent = ($value-$start)*100/($end-$start);

		if($percent > 100) return 100; 
		if($percent < 0) return 0; 
		return round($percent, 0);
	}

	/**
	 * Return this spot's online status
	 */
	public function getOnlineAttribute() 
	{
		return ((Carbon::now()->subSeconds(30)->lt(Carbon::parse($this->updated_at))) ? "<span class='spot-status spot-status-online'>Online</span>" : "<span class='spot-status spot-status-offline'>Offline</span>");
	}

	/**
	 * Returns spots that have roaming sensors in its jobs
	 */
	public static function getRoamingSpots() 
	{
		$spots = DB::table('Spot')
			->join('Basestation', 'Spot.basestation_id', '=', 'Basestation.id')
			->join('Users', 'Users.id', '=', 'Basestation.user_id')
            ->join('Object', 'Spot.id', '=', 'Object.spot_id')
            ->join('Job', 'Object.id', '=', 'Job.object_id')
            ->join('Sensor', 'Job.sensor_id', '=', 'Sensor.id')
            ->where('Sensor.title', '=', 'Roaming Spot')
            ->where('Users.id', '=', Auth::user()->id)
            ->groupBy('Spot.id')
            ->get();
        $collection = new \Illuminate\Database\Eloquent\Collection;
        foreach ($spots as $spot) {
        	$collection->add(Spot::find($spot->spot_id));
        }

        return $collection->reverse();
	}

	/**
	 * Returns spots that have cell towers in its jobs
	 */
	public static function getTowerSpots() 
	{
		$spots = DB::table('Spot')
			->join('Basestation', 'Spot.basestation_id', '=', 'Basestation.id')
			->join('Users', 'Users.id', '=', 'Basestation.user_id')
            ->join('Object', 'Spot.id', '=', 'Object.spot_id')
            ->join('Job', 'Object.id', '=', 'Job.object_id')
            ->join('Sensor', 'Job.sensor_id', '=', 'Sensor.id')
            ->where('Sensor.title', '=', 'Cell Tower')
            ->where('Users.id', '=', Auth::user()->id)
            ->groupBy('Spot.id')
            ->get();
        $collection = new \Illuminate\Database\Eloquent\Collection;
        foreach ($spots as $spot) {
        	$collection->add(Spot::find($spot->spot_id));
        }
        
        return $collection->reverse();
	}

	/**
	 * Returns spots that don't have an object assigned
	 */
	public static function getNonObjectSpots() 
	{
		$collection = new \Illuminate\Database\Eloquent\Collection;
        foreach (Spot::all() as $spot) {
        	if(!isset($spot->object->id))
        		$collection->add($spot);
        }
        
        return $collection;
	}

	/**
	 * Returns spots that have cell towers in its jobs, and that do not have a zone assigned
	 */
	public static function getTowerSpotsNoZoneNoObjectZone() 
	{
		$spots = DB::table('Spot')
			->join('Basestation', 'Spot.basestation_id', '=', 'Basestation.id')
			->join('Users', 'Users.id', '=', 'Basestation.user_id')
            ->join('Object', 'Spot.id', '=', 'Object.spot_id')
            ->join('Job', 'Object.id', '=', 'Job.object_id')
            ->join('Sensor', 'Job.sensor_id', '=', 'Sensor.id')
            ->where('Sensor.title', '=', 'Cell Tower')
            ->where('Users.id', '=', Auth::user()->id)
            ->groupBy('Spot.id')
            ->get();
        $collection = new \Illuminate\Database\Eloquent\Collection;
        foreach ($spots as $spot) {
        	if(!isset(Spot::find($spot->spot_id)->object->zone->id) && !isset(Spot::find($spot->spot_id)->object->zoneobject->id))
        		$collection->add(Spot::find($spot->spot_id));
        }
        
        return $collection->reverse();
	}

}

app/views/touch/panels/actuators.blade.php
<div class='panel panel-default draggable'>
	<div class='dock text-center'>
		<p> Actuators </p>
	</div>
	<div class='panel-heading handle'>
		Actuators
	</div>
	<table class='table table-striped table-condensed' id ="table_actuator">
		<thead>
			<tr>
				<th><small>Actuator</small></th>
				<th><small>Control</small></th>
			</tr>
		</thead>
		<tbody>
			@foreach (Actuator::all() as $actuator)
				<tr>
					<td> 
						<small>
							<span class='text-muted'>
								@if(isset($actuator->triggers))
									{{ $actuator->triggers }}<br />
									<small><a href='{{ url("actuators/$actuator->id") }}'>{{ $actuator->actuator_address }}</a></small>
								@else
									<a href='{{ url("actuators/$actuator->id") }}'>{{ $actuator->actuator_address }}</a>
								@endif
							</span>
						</small>
					</td>
					<td> 
						<div class="btn-group" data-toggle="buttons">
						  <label class="btn btn-sm btn-primary active actuator-status" data-actuator-status="auto" data-actuator-id="{{ $actuator->id }}">
						    <input type="radio" autocomplete="off" checked> Auto
						  </label>
						  <label class="btn btn-sm btn-default actuator-status" data-actuator-status="on" data-actuator-id="{{ $actuator->id }}">
						    <input type="radio" autocomplete="off"> On
						  </label>
						  <label class="btn btn-sm btn-default actuator-status" data-actuator-status="off" data-actuator-id="{{ $actuator->id }}">
						    <input type="radio" autocomplete="off"> Off
						  </label> 
						</div>
						<script type="text/javascript">
							$('.actuator-status').click(function(e) {
								var button = $(e.target);
								console.log(button.data('actuator-status'));
								$.ajax({
								  type: "POST",
								  url: "actuators/set_status",
								  data: {status: button.data('actuator-status'), id: button.data('actuator-id')},
								  success: function(data) {
								  	console.log(data);
								  }
								});
							});
						</script>
					</td>
				</tr>
			@endforeach
		</tbody>
	</table>
</div>

app/views/touch/panels/battery.blade.php
<div id='panel_{{ $spot->id }}_battery'>
	<div class='battery-container'>
		<span class='battery-percent'>{{ $spot->battery_percent }}%</span> 
		<span class='battery' style='width:{{ (($percent) ? $percent/2.1739130435 : 0) }}px'></span>
		{{ $spot->online }}
	</div>
</div>

app/views/touch/panels/modal_spot.blade.php
<div class="modal fade" id="modal-spot-{{ $spot->id }}" tabindex="-1" role="dialog" aria-labelledby="modal-spot-{{ $spot->id }}Label" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">

      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="modal-spot-{{ $spot->id }}Label">{{ $spot->object->title }}  &middot; <a href='{{ url("spots/".$spot->id."")}}'>{{ $spot->spot_address}}</a></h4>
      </div>
      <div class="modal-body">
      	@include('touch.panels.spot') 
      </div>

      <div class="modal-footer">
      	<div class='pull-right'>
			@include('touch.panels.battery', array('percent' => $spot->battery_percent))
		</div>
      </div>

    </div>
  </div>
</div>

app/views/touch/panels/spot.blade.php
<div class='tabpanel draggable'>
	@if(count($spot->jobs))
		<ul class="nav nav-tabs minimisable" role="tablist">
			<?php $count = 1; ?>
			@if($spot->isSmartCup())
				<li role="presentation" class='{{ ($count == 1) ? "active" : "" }}'>
					<a href="#{{ $spot->id }}_water" data-target="#{{ $spot->id }}_water" aria-controls="{{ $spot->id }}_water" role="tab" data-toggle="tab">
						<small>Smart Cup</small>
					</a>
				</li>
				<?php $count++ ?>
			@endif
			@foreach($spot->jobs as $job)
				<li role="presentation" class='{{ ($count == 1) ? "active" : "" }}'>
					<a href="#{{ $spot->id }}_{{$job->id }}" data-target="#{{ $spot->id }}_{{$job->id }}" aria-controls="{{ $spot->id }}_{{$job->id }}" role="tab" data-toggle="tab">
						<small>{{$job->sensor->measures }}</small>
					</a>
				</li>
				<?php $count++; ?>
			@endforeach
		</ul>
		<div class='tab-content minimisable'>
		<?php $count = 1; ?>
			@if($spot->isSmartCup())
				<div role='tabpanel' class='tab-pane {{ ($count == 1) ? "active" : "fade" }}' id="{{ $spot->id }}_water">
					<div class='row'>
						<br /> 
						<div class='col-xs-offset-1 col-xs-3 text-left'>
							<h2> <span class='water_level'>330ml</span> <br /><small>Left in cup</small></h2>
						</div>
						<div id="CupOfCoffee" class='col-xs-4'>
							<div id="lid">
								<div class="top"></div>
								<div class="lip"></div>
							</div>
							<div id="cup">
								<div id='water'></div>
							</div>
							<div id="sleeve"></div>
						</div>
						<div class='col-xs-3 text-right'>
							<h2 class='text-right'> 
								<span id='cup_no'>{{ Water::whereWaterPercent('0')->whereBetween('created_at', array(Carbon::now()->startOfDay()->toDateTimeString(), Carbon::now()->endOfDay()->toDateTimeString()))->get()->count() }}</span>/6 cups<br />
								<small>Drank today</small>
							</h2>
						</div>
					</div>
					<br />
				</div>
				<?php $count++ ?>
			@endif
			@foreach($spot->jobs as $job)
				@include('touch.tables.zonejob')
				<?php $count++ ?> 
			@endforeach
		</div>
	@endif
</div>

app/views/touch/panels/zone.blade.php
@foreach($zone->zoneobjects as $zone_object)
	@if(isset($zone_object->object->spot->id))
		<button type="button" class='draggable-object panel object-spot-{{ $zone_object->object->spot->id }}' data-toggle="modal" data-target="#modal-spot-{{ $zone_object->object->spot->id }}" style='{{ $zone_object->style }} line-height: {{ ($zone_object->height - 8) }}px'>
			{{ $zone_object->object->title }}
		</button>
	@endif
@endforeach
<div class='panel panel-default panel-top'>
	<div class='panel-body text-center'>
		@include('touch.panels.zonelatest')
	</div>
</div>
<div class='draggable-zone-title'>
	{{ $spot->object->title }} 
	<a class='' href='{{ url('objects/'.$spot->object->id.'/edit') }}'>
		<span class='glyphicon glyphicon-pencil'></span> 
	</a>	
	<br />
	<small class='text-muted'>
		<a href='{{ url('spots/'.$spot->id) }}'>{{ $spot->spot_address }}</a>
	</small>
</div>
<div class='panel panel-default panel-bottom'>
	@include('touch.tables.zonechange')
</div>

app/views/touch/panels/zonelatest-min.blade.php
<div class='text-center' id='panel_{{ $spot->id }}_zonelatest_min'>
	<p>
		<small>
			<span class='glyphicon glyphicon-fire'></span> {{ $spot->object->getLatestHeat() }} <span class='glyphicon glyphicon-flash'></span> {{ $spot->object->getLatestLight() }}
		</small>
	</p> 
</div>

app/views/touch/panels/zonelatest.blade.php
<div class='text-center' id='panel_{{ $spot->id }}_zonelatest'>
	<div class='col-md-7'>
		<span class='glyphicon glyphicon-fire'></span> <span class='{{ $spot->id }}_heat'>{{ $spot->object->getLatestHeat(isset($limit) ? $limit : null) }}</span>
	</div> 
	<div class='col-md-5'>
		<span class='glyphicon glyphicon-flash'></span> <span class='{{ $spot->id }}_light'>{{ $spot->object->getLatestLight(isset($limit) ? $limit : null) }}</span>
	</div>
</div>

app/views/touch/panels/zones.blade.php
<div class='panel panel-default draggable'>
	<div class='panel-heading handle'>
		<a href='{{ url("zones/configure") }}' class='btn btn-default btn-xs pull-right'>
			<span class='glyphicon glyphicon-cog'></span> Configure Zones
		</a>
		Zones
	</div>
	<div class='panel-body zones-container'>
		@foreach(Zone::all() as $zone)
			@if(isset($zone->object->spot->id))
				<div class="draggable-zone draggable-zone-{{ $zone->object->spot->id }}" style="{{ $zone->style }}">
						@include('touch.panels.zone', array('spot' => $zone->object->spot))
				</div>
			@endif
		@endforeach
		<div id="guide-h" class="guide"></div>
		<div id="guide-v" class="guide"></div>
	</div>
</div>